project:
  type: website
  output-dir: _site

website:
  title: "Energy Production Analysis"
  navbar:
    left:
      - href: test.qmd
        text: Home
      - about.qmd
      - sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto